apiVersion: v1
kind: Secret
metadata:
  name: tasklist-secrets
  namespace: tasklist
type: Opaque
stringData:
  # For Kubernetes - connect to external Postgres via service
  datasource-url: jdbc:postgresql://postgres-db:5432/tasklist_db
  # Alternative if using endpoint service
  # datasource-url: jdbc:postgresql://postgres-db-endpoint:5432/tasklist_db
  
  datasource-username: postgres
  datasource-password: mypassword
  jwt-secret: myVerySecretKeyForJWTTokenGenerationAndValidationPleaseChangeThisInProduction123456789